version: "3"

services:
  app:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./application:/var/www/html
    networks:
      - appnet

  server:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./application:/var/www/html
    ports:
      - 80:80
    networks:
      - appnet

  custom-app:
    build:
      context: docker/custom-fpm
      dockerfile: Dockerfile
    image: laravel_custom_fpm:latest
    volumes: 
      - ./application:/var/www/html:cached
      - ./docker/custom-fpm/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/custom-fpm/fpm-pool.conf:/etc/php7/php-fpm.d/www.conf
      - ./docker/custom-fpm/php.ini:/etc/php7/conf.d/custom.ini
    ports: 
      - 81:8080
    networks: 
      - appnet    
      
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - appnet

  cache:
    image: redis:alpine
    volumes:
      - cachedata:/data
    ports: 
      - 6379:6379
    networks:
      - appnet

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    user: node
    volumes:
      - .:/var/www/html
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"

volumes:
  dbdata:
    driver: "local"
  cachedata:
    driver: "local"
